blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Quick Note
    url: https://github.com/SangHyeok/Castle-Lord-Tycoon/issues/new
    about: ê°„ë‹¨í•œ ë©”ëª¨ë‚˜ ì•„ì´ë””ì–´ëŠ” ë¹ˆ ì´ìŠˆë¡œ ì‘ì„±í•˜ì„¸ìš”
